spring.application.name=urlshortener
spring.data.mongodb.uri=mongodb://localhost:27017/urlshortener
app.snowflake.machine-id=1
spring.redis.host=redis-14636.crce182.ap-south-1-1.ec2.cloud.redislabs.com
spring.redis.port=14636
spring.redis.password=E2zUqPtchdt5GcrfA3jVCz96ykdD8HGK
spring.redis.ssl.enabled=true