spring.application.name=urlshortener
spring.data.mongodb.uri=mongodb://localhost:27017/urlshortener
#spring.data.mongodb.uri=mongodb+srv://op1pradeep007_db_user:Pradeep007@cluster0.rmem69a.mongodb.net/?appName=Cluster0
app.snowflake.machine-id=1
spring.data.redis.host=redis-14636.crce182.ap-south-1-1.ec2.cloud.redislabs.com
spring.data.redis.port=14636
spring.data.redis.password=E2zUqPtchdt5GcrfA3jVCz96ykdD8HGK
spring.data.redis.ssl.enabled=false